
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INC_DEC = 26;
  public static final int LBRACKET = 35;
  public static final int COMP_OP = 29;
  public static final int STRING_TEXT = 24;
  public static final int TRUE_FALSE = 23;
  public static final int CONTINUE = 14;
  public static final int FOR = 4;
  public static final int WRITE = 19;
  public static final int STATIC = 8;
  public static final int NOT = 30;
  public static final int SEMICOLON = 33;
  public static final int RPAR = 38;
  public static final int COMMA = 31;
  public static final int CLASS = 16;
  public static final int FLOAT_NUMBER = 22;
  public static final int ASSIGN = 25;
  public static final int MAIN = 18;
  public static final int IF = 2;
  public static final int THIS = 9;
  public static final int ID = 40;
  public static final int DOT = 32;
  public static final int PRI_TYPE = 41;
  public static final int EOF = 0;
  public static final int RETURN = 15;
  public static final int RBRACKET = 34;
  public static final int NEW = 12;
  public static final int error = 1;
  public static final int LBLOCK = 37;
  public static final int BREAK = 7;
  public static final int VOID = 10;
  public static final int RBLOCK = 36;
  public static final int MATH_OP = 27;
  public static final int LOGIC_OP = 28;
  public static final int ELSE = 5;
  public static final int READ = 20;
  public static final int WHILE = 3;
  public static final int DEFAULT = 13;
  public static final int INT_NUMBER = 21;
  public static final int PUBLIC = 11;
  public static final int THEN = 6;
  public static final int EXTENDS = 17;
  public static final int LPAR = 39;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "WHILE",
  "FOR",
  "ELSE",
  "THEN",
  "BREAK",
  "STATIC",
  "THIS",
  "VOID",
  "PUBLIC",
  "NEW",
  "DEFAULT",
  "CONTINUE",
  "RETURN",
  "CLASS",
  "EXTENDS",
  "MAIN",
  "WRITE",
  "READ",
  "INT_NUMBER",
  "FLOAT_NUMBER",
  "TRUE_FALSE",
  "STRING_TEXT",
  "ASSIGN",
  "INC_DEC",
  "MATH_OP",
  "LOGIC_OP",
  "COMP_OP",
  "NOT",
  "COMMA",
  "DOT",
  "SEMICOLON",
  "RBRACKET",
  "LBRACKET",
  "RBLOCK",
  "LBLOCK",
  "RPAR",
  "LPAR",
  "ID",
  "PRI_TYPE"
  };
}

