enum TokenType {
    IF, WHILE, FOR, ELSE, THEN, BREAK, STATIC, VOID, PUBLIC, DEFAULT, CONTINUE, RETURN,
    LONG, INT, STRING, CHAR, BOOLEAN, DOUBLE, FLOAT,STRING_TEXT,
    ID, NUMBER,
    ASSIGN,
    PLUS,MINUS,MUL,DIV,MOD,AND,OR,
    EQ,NEQ,LT,GT,LTEQ,GTEQ,
    INC,DEC,
    TRUE,FALSE,
    COMMA,SEMICOLON,RBRACKET,LBRACKET,RBLOCK,LBLOCK,RPAR,LPAR

}
